import { APP_ID } from "@/api/instances/socialDummyApi";
import { postService } from "@/api/services";
import { ThemeManagerProvider } from "@/contexts/ThemeManager/ThemeManager.context";
import { KanbanBoardLayout } from "@/layouts/KanbanBoard/KanbanBoard.layout";
import MainView from "@/views/Main.view";
import { MainSecondView } from "@/views/MainSecond.view";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Elice Twitter",
  description: "Generated by create next app",
};

export default async function Home() {
  const res = await fetch("https://dummyapi.io/data/v1/post", {
    headers: {
      "app-id": APP_ID,
    },
    cache: "no-cache",
  });

  const data = await res.json();

  return (
    <KanbanBoardLayout posts={(data as any).data}>
      {/* <MainView /> */}
      {/* <MainSecondView /> */}
    </KanbanBoardLayout>
  );
}
